### ISSUE TITLE
Doesn't work locally?

### ISSUE THREAD

**Issue by petermorlion** [stackimpact/stackimpact-nodejs#5]
Is it possible this doesn't work when I run my application locally? I created an `index.js` file with the contents of [this post](https://stackimpact.com/blog/aws-lambda-cpu-and-memory-profiling-node-js/). I then created a serverless yaml file with this:

```
# For full config options, check the docs: docs.serverless.com

service: stackimpact-spike  

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 10 # Avoid cold start timeouts.
  region: ${opt:region}
  stage: ${opt:stage}

functions:
  main:
    handler: index.handler
    memorySize: 256
    events:
      - http: ANY {proxy+}

plugins:
  - serverless-offline
```

I've also done `npm install` for `serverless`, `stackimpact`, and `serverless-offline`.

Finally, I've entered the key as I can see in my StackImpact configuration tab.

When I run it with `./node_modules/serverless/bin/serverless offline`, I can make successfull requests, but nothing comes in my StackImpact dashboard (on any tab). All I see is a message "It may take a few minutes for the first time data to be available."

After my first request, I can see this in the console:
```
[13:48:47.684] StackImpact 1.3.10: Agent activated.
```

I've also run a  tool that made 2453 (successful) requests, and I've waited for quite some time now. I still don't see anything in the dashboard.

At the end, I see an error:
```
[13:57:03.613] StackImpact 1.3.10: Error uploading messages to the dashboard, backing off next upload
[13:57:03.614] StackImpact 1.3.10: connect ECONNREFUSED 127.0.0.1:443
[13:57:03.614] StackImpact 1.3.10: Error: connect ECONNREFUSED 127.0.0.1:443
```

I've seen #2 but that author mentions the wrong positioning of `stackimpact.start`. However, I've followed the blog post and put it outside my handler.

This all makes me think StackImpact doesn't work for locally running applications? Or am I doing something wrong?

**Comment by dmelikyan** [comment]
The agent cannot connect to the dashboard due to a connection issue, most likely because of a proxy. Can you make sure the agent connects to the dashboard directly? Otherwise, proxy support is currently planned for the Node.js agent.

**Comment by petermorlion** [comment]
Well, this is the output of my logging after my first request:

![capture](https://user-images.githubusercontent.com/3483719/49579694-46c65080-f94d-11e8-8238-ea32cd16c05e.PNG)

So I'm assuming it made a successful call to stackimpact. I have no proxy configured.

Here's the logging after some requests:

![capture2](https://user-images.githubusercontent.com/3483719/49579779-85f4a180-f94d-11e8-8ea3-274711089107.PNG)

I have no idea why it's trying to connect to 127.0.0.1, except for the fact that I'm running locally? Or is it because of https (I notice it's using port 443)?

**Comment by dmelikyan** [comment]
The agent only connects to https://agent-api.stackimpact.com to load configuration and upload data. Can you post or send us the code where you initialize and call the agent methods (please remove all keys, credentials, etc.)?

**Comment by petermorlion** [comment]
I've created a [repo with the code](https://github.com/petermorlion/stackimpact-spike). You can test it with:

```
npm install
npm start
```

Then navigate to `localhost:3000`.

**Comment by dmelikyan** [comment]
There was an issue with agent startup specific to the serverless-offline environment, which should be fixed now in the agent v1.3.11.

**Comment by petermorlion** [comment]
Hm, I no longer get an error, but after multiple requests, I still don't see anything in my account.

**Comment by dmelikyan** [comment]
Did the requests continue over a few minutes? If not, please try to simulate a few minutes of constant traffic. The agent relies on requests to report profiles (due to Lambda process freeze in-between).

**Comment by petermorlion** [comment]
I had manually launched some requests and didn't see anything. After trying again and using a load testing tool for 5 minutes, I have some data. Thanks!
